### ISSUE TITLE
About the ui of SubCategories (AI)

### ISSUE THREAD

**Issue by YumeMienai** [IllusionMods/IllusionModdingAPI#11]
When the scrollbar display, the MakerButton, MakerRadioButtons and maybe something else will be cut a little at the right side.
Also can MakerRadioButtons just show the buttons rather combine with the setting name like the original game?

**Comment by ManlyMarco** [comment]
The slight cutting off I know about. It was fiddly to fix, so I left it as it is for now. I'll revisit this later when doing some work around the code.

At the moment the text label is mandatory. If any plugin needs to hide it to show more buttons I can add it in a later version, just let me know.

**Comment by YumeMienai** [comment]
Got it. I just test is pushUp compatible with MoreAccessories, and see a hole "in front of" the MakerRadioButtons. Check the code and found the author just pass empty string to make setting name to nothing display. 🤣

**Comment by ManlyMarco** [comment]
While we're at it there's also the issue that there is no background in these custom mod categories.

**Comment by ManlyMarco** [comment]
Fixed in #46
