### ISSUE TITLE
ReloadCustomInterface fires too early (KK)

### ISSUE THREAD

**Issue by jalil49** [IllusionMods/IllusionModdingAPI#28]
> Fired after character or coordinate is loaded in maker, after all controllers had their events fired. This event is only fired when inside the character maker. Use this to update values of custom controls. EventArgs can be either KKAPI.Chara.CharaReloadEventArgs or KKAPI.Chara.CoordinateEventArgs depending on why the reload happened.

From my understanding this event should fire once a coordinate is loaded, but running into an issue where I get an error because there are not enough accessory slots available when this fired. 

> "accessoryIndex has to be between 0 and AccessoriesApi.GetCvsAccessoryCount() - 1"

suggestion: adding a coroutine to check the CVS count and the expected count
idea
```cs
if (ReloadCustomInterface != null)
{
    WeakKeyDictionary<ChaFile, MoreAccessories.CharAdditionalData> _accessoriesByChar = (WeakKeyDictionary<ChaFile, MoreAccessories.CharAdditionalData>)Traverse.Create(MoreAccessories._self).Field("_accessoriesByChar").GetValue();
    if (_accessoriesByChar.TryGetValue(ChaFileControl, out MoreAccessories.CharAdditionalData data) == false)
    {
        data = new MoreAccessories.CharAdditionalData();
        _accessoriesByChar.Add(ChaFileControl, data);
    }
    int ACCData = 20+data.nowAccessories.Count;
    
    while (AccessoriesApi.GetCvsAccessoryCount() < ACCData)
    {
        yield return 0;
    }

    foreach (var handler in ReloadCustomInterface.GetInvocationList())
    {
        try
        {
            ((EventHandler)handler).Invoke(KoikatuAPI.Instance, args);
        }
        catch (Exception e)
        {
            KoikatuAPI.Logger.LogError(e);
        }
    }
}
```

**Comment by ManlyMarco** [comment]
This event is supposed to be the same as the events on chara controllers, so it can't be changed much without potentially breaking something. I think this should be done inside a plugin if it needs this particular timing, or as a separate event, in which case it would need to be made consistent between games.

**Comment by jalil49** [comment]
hmm moreaccessories is still adding slots by the time this event fires so reloading my custom interface that uses accessory slots has issues when loading a new character/coordinate that has more slots than available.
