### ISSUE TITLE
[KK] GameAPI still not working in VR (?)

### ISSUE THREAD

**Issue by Sauceke** [IllusionMods/IllusionModdingAPI#41]
I still can't get OnStartH to get triggered by VR events. [This fix](https://github.com/IllusionMods/IllusionModdingAPI/commit/9e53580d972ce258f4a06b5ae1d74f2b86415db7) doesn't seem to be patching the correct methods. I think AccessTools.Method needs to be given the type as well as the method name.

Also, VRHScene doesn't extend HSceneProc in KK, so I doubt the fix could be this easy. A lot of fields present in HSceneProc are missing from VRHScene, and some fields that they do share have different access levels. Don't see a trivial conversion from one to the other so that you could pass it to OnStartH with its current signature.

**Comment by ManlyMarco** [comment]
Looks like a typo, this should fix it [KKAPI_1.21.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/6985399/KKAPI_1.21.zip)

**Comment by Sauceke** [comment]
It doesn't, and Hooks.SetupHooks isn't even getting called anymore because of [this](https://github.com/IllusionMods/IllusionModdingAPI/commit/320a09635d8242bc52a30ac55aae1c4e5efa8751#diff-6196bf6748fbbaacfc9965b28b42eb9467979454958d0702688c45d251a0e13bL118).
But there is a more basic problem why this probably won't be possible. I'll DM you the VRHScene disassembly.

**Comment by Sauceke** [comment]
That fixed it, thank you.
