### ISSUE TITLE
KKS Failed to edit card in story model, likely to be a API problem?

### ISSUE THREAD

**Issue by Vincentfan0705** [IllusionMods/IllusionModdingAPI#53]
I have a card that could be read and edited in Chara maker as normal, no error reports, but in story model if I want to edit the card then it would become endless loading of maker interface, the output log has a bug report for KK_API. attached is the card and output log. KKS_API is the latest version.
[output_log.txt](https://github.com/IllusionMods/IllusionModdingAPI/files/7490858/output_log.txt)

[Koikatu_F_20201212222030045_Abigai.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/7490861/Koikatu_F_20201212222030045_Abigai.zip)

**Comment by ManlyMarco** [comment]
Fixed in https://github.com/ManlyMarco/MoreAccessoryParents/releases/tag/v2.0.1
