### ISSUE TITLE
Api conflictions causing white screen on start

### ISSUE THREAD

**Issue by Hordeimperial** [IllusionMods/IllusionModdingAPI#55]
I'm new to honey select two and I've come across an issue where I apparently need two conflicting modding APIs. In order to use the majority of mods for HS2 I need the HS2 API. However, for the almost necessary mod [Uncensor Selector] I apparently need the KK API and if I have two of them in the plugin file the game stops loading and produces an indefinite white screen on startup. How do I use both, or alternatively what else could be going wrong that I could fix.

**Comment by IDontHaveIdea** [comment]
Hi,

HS2API is the only one you need although is called HS2API internally the name is KKAPI.  This API works for many games HS2API.dll for HS2, AIAPI.dll for AI-Shoujo, KKAPI.dll for Koikatsu, etc.

The dll names are different but the plugins that use the API for the various games always refer to it with the name KKAPI.

**Comment by Hordeimperial** [comment]
Thank you so much! I'll get the newest version of HS2API and see how it goes.

**Comment by Hordeimperial** [comment]
Thanks, I had to look a bit harder for version 1.28 of the API but it works now.
