### ISSUE TITLE
For Material editor, make shader set to a specific chosen shader on clothes selection

### ISSUE THREAD

**Issue by MonkeyDocs** [IllusionMods/IllusionModdingAPI#74]
Shader right now reverts to AIT/Clothes everytime you select another cloth

**Comment by ManlyMarco** [comment]
I have no idea what you mean. This repo is for the API not MaterialEditor.

**Comment by MonkeyDocs** [comment]
> I have no idea what you mean. This repo is for the API not MaterialEditor.

Sorry, posted in the wrong section
