### ISSUE TITLE
更新api之后进入实验室老是白屏卡顿，  但我暂时无法判断这两者是否关联，  仅仅是发布看看看看是否有其他人遇到相同问题

### ISSUE THREAD

**Issue by fateyoujo** [IllusionMods/IllusionModdingAPI#75]
After updating the API, the laboratory often shows a white screen and becomes unresponsive. However, I cannot determine if these issues are related. I'm just posting this to see if anyone else has encountered the same problem.

**Comment by fateyoujo** [comment]
studio

**Comment by ManlyMarco** [comment]
Send the output_log.txt file after the white screen happens.
