### ISSUE TITLE
Regression in 1.42: "Screen Effect/Viewport/Content/Sky/Pattern/Dropdown" doesn't exist in KK

### ISSUE THREAD

**Issue by Kokaiinum** [IllusionMods/IllusionModdingAPI#78]
As the title says. 2ba9ed373d2d9819c4a76dbefe6ef6a145969208 introduces some changes for dropdowns, but the element it clones for dropdowns, "Screen Effect/Viewport/Content/Sky/Pattern/Dropdown", is not present in KK. This causes an exception to be thrown when SceneEffectsCategory.Initialize() is run, and since that's not caught this breaks any plugin relying on it, such as StudioSceneSettings.

**Comment by ManlyMarco** [comment]
@krypto5863
